name: mlapi

channels:
- conda-forge
- anaconda 

dependencies:
# Essential
- python==3.9
- pip==22.2.1
- ipython==8.4.0
- tqdm==4.64.0
# Data Science
- numpy==1.23.1
- scipy==1.8.1
- pandas==1.4.3
# Machine Learning
- scikit-learn==1.0.2
- scikit-optimize==0.9.0

- pip:
  # Machine Learning
  - jcopml==1.2.0
  - luwiji==1.2.0
  # API
  - fastapi
  - "uvicorn[standard]"
  - nltk 